### ISSUE TITLE
Multiple deprecation issues in homebrew

### ISSUE THREAD

**Issue by selfagency** [michaeldfallen/butler#13]
```
==> Installing butler from michaeldfallen/formula
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/butler.rb:6:in `<class:Butler>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/butler.rb:6:in `<class:Butler>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/butler.rb:6:in `<class:Butler>'
Please report this to the michaeldfallen/formula tap!

==> Downloading https://bintray.com/artifact/download/michaelallen/homebrew-releases/butler-0.7.tar.gz
==> Downloading from https://dl.bintray.com/michaelallen/homebrew-releases/butler-0.7.tar.gz
######################################################################## 100.0%
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/usr/local/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

==> Bash and Zsh completion

To enable completion add:

    source "$(butler --init-completion)"

To your ~/.bashrc or ~/.zshrc
🍺  /usr/local/Cellar/butler/0.7: 9 files, 8.7K, built in 2 seconds
```

**Comment by michaeldfallen** [comment]
Fixed by the merge of https://github.com/michaeldfallen/homebrew-formula/pull/7.

Thanks for raising this. Closing.
